
REVOKE EXECUTE ON FUNCTION public.current_role_key() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.has_role(text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.has_any_role(text[]) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_admin() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_staff() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.handle_new_auth_user() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.protect_last_super_admin() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.block_audit_mutation() FROM PUBLIC;
